apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.minecraft.name }}
  labels:
    app: {{ .Values.minecraft.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.minecraft.port }}
      protocol: UDP
  selector:
    app: {{ .Values.minecraft.name }}
