kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.minecraft.name }}-data-pvc
spec:
  storageClassName: {{ .Values.volume.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
